"""Test case definitions for deepeval.

This module provides the core data structures used to represent
LLM test cases for evaluation.
"""

from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Union


@dataclass
class LLMTestCaseParams:
    """Parameters that can be used in LLM test case evaluation."""

    INPUT = "input"
    ACTUAL_OUTPUT = "actual_output"
    EXPECTED_OUTPUT = "expected_output"
    CONTEXT = "context"
    RETRIEVAL_CONTEXT = "retrieval_context"
    TOOLS_CALLED = "tools_called"
    EXPECTED_TOOLS = "expected_tools"


@dataclass
class LLMTestCase:
    """Represents a single test case for evaluating an LLM.

    Attributes:
        input: The input prompt or query sent to the LLM.
        actual_output: The actual response generated by the LLM.
        expected_output: The expected or ideal response (optional).
        context: Background context provided to the LLM (optional).
        retrieval_context: Retrieved documents used for RAG evaluation (optional).
        tools_called: List of tools the LLM called during generation (optional).
        expected_tools: List of tools expected to be called (optional).
        additional_metadata: Any extra metadata associated with the test case.
        comments: Human-readable notes about the test case.
        _dataset_rank: Internal rank used when part of a dataset.
    """

    input: str
    actual_output: str
    expected_output: Optional[str] = None
    context: Optional[List[str]] = None
    retrieval_context: Optional[List[str]] = None
    tools_called: Optional[List[str]] = None
    expected_tools: Optional[List[str]] = None
    additional_metadata: Optional[Dict[str, Any]] = field(default_factory=dict)
    comments: Optional[str] = None
    _dataset_rank: Optional[int] = field(default=None, repr=False)

    def __post_init__(self):
        """Validate fields after initialization."""
        if not isinstance(self.input, str):
            raise TypeError(f"'input' must be a string, got {type(self.input).__name__}")
        if not isinstance(self.actual_output, str):
            raise TypeError(
                f"'actual_output' must be a string, got {type(self.actual_output).__name__}"
            )
        if self.context is not None and not isinstance(self.context, list):
            raise TypeError("'context' must be a list of strings or None")
        if self.retrieval_context is not None and not isinstance(self.retrieval_context, list):
            raise TypeError("'retrieval_context' must be a list of strings or None")


@dataclass
class ConversationalTestCase:
    """Represents a multi-turn conversational test case.

    Attributes:
        turns: A list of LLMTestCase objects representing each turn in the conversation.
        additional_metadata: Any extra metadata associated with the conversation.
        comments: Human-readable notes about the test case.
        _dataset_rank: Internal rank used when part of a dataset.
    """

    turns: List[LLMTestCase]
    additional_metadata: Optional[Dict[str, Any]] = field(default_factory=dict)
    comments: Optional[str] = None
    _dataset_rank: Optional[int] = field(default=None, repr=False)

    def __post_init__(self):
        """Validate that turns is a non-empty list of LLMTestCase objects."""
        if not isinstance(self.turns, list) or len(self.turns) == 0:
            raise ValueError("'turns' must be a non-empty list of LLMTestCase objects")
        for i, turn in enumerate(self.turns):
            if not isinstance(turn, LLMTestCase):
                raise TypeError(
                    f"Each turn must be an LLMTestCase instance, "
                    f"got {type(turn).__name__} at index {i}"
                )


# Type alias for convenience
TestCase = Union[LLMTestCase, ConversationalTestCase]
